trigger:
- main
pool:
  vmImage: 'ubuntu-1604' 

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Free Trial(21ffa5d8-e7c7-481b-8a23-e5f94872f1fd)'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az acr login --name ACRlearning
      docker login ACRlearning
      docker build -t nginx .
      docker push ACRlearning.azurecr.io/nginx