trigger:
        - main
        pool:
          vmImage: 'ubuntu-1604' 

        variables:
          imageName: 'Shazikura.pipelines-python-django'

        steps:
        - task: Docker@2
          displayName: Build an image
          inputs:
            repository: $(imageName)
            command: build
            Dockerfile: app/Dockerfile

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "Hello World"