trigger:
- main
pool:
  vmImage: 'ubuntu-1604' 

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: 
    command: build
    Dockerfile: app/Dockerfile

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "Hello World"